theme: jekyll-theme-minimal
title: How to build a bioinformatics workstation in two steps
# logo: https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Tool_box_icon-01.svg/165px-Tool_box_icon-01.svg.png
google_analytics: G-1LLWRMJVVF
